apiVersion: v1
kind: Service
metadata:
  name: abstergo-corp-app-service
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32393  # Port your app is exposed on
  type: NodePort
